POST http://localhost:4400/api/user/register
Content-Type: application/json

{
    "fullname":"duykhuong",
    "password":"123456",
    "gender":1,
    "email":"leduykhuonggcd@gmail.com",
}

###
POST http://localhost:4400/api/user/login
Content-Type: application/json

{
   
    "password":"123456",
  
    "email":"leduykhuonggcd@gmail.com"
    
}

###
GET  http://localhost:4400/api/user/getall?keyword=khuong
